name: it-tools
services:
    it-tools:
        image: it-tools:local # ghcr.io/corentinth/it-tools:latest
        container_name: it-tools
        # ports:
            # - "1002:80"
        restart: unless-stopped
        networks:
            - reverse_proxy

networks:
    reverse_proxy:
        external: true
