services:
    caddy:
        container_name: searxng_caddy
        image: docker.io/library/caddy:2-alpine
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./data/Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy-data:/data:rw
            - caddy-config:/config:rw
        environment:
            - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-localhost:80}
            - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"

    redis:
        container_name: searxng_redis
        image: docker.io/valkey/valkey:8-alpine
        command: valkey-server --save 30 1 --loglevel warning
        restart: unless-stopped
        networks:
            - searxng
        volumes:
            - valkey-data:/data
        cap_drop:
            - ALL
        cap_add:
            - SETGID
            - SETUID
            - DAC_OVERRIDE
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1m
            timeout: 5s
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"

    searxng:
        container_name: searxng
        image: docker.io/searxng/searxng:latest
        restart: unless-stopped
        networks:
            - searxng
            - reverse_proxy
        # ports:
            # - ${SEARXNG_HTTP_PORT}:8080
        volumes:
            - ./data:/etc/searxng:rw
        environment:
            - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/search
            - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
            - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "1"

networks:
    searxng:
        name: searxng_network
    reverse_proxy:
        external: true

volumes:
    caddy-data:
    caddy-config:
    valkey-data:
