services:
    actual_server:
        image: docker.io/actualbudget/actual-server:latest
        container_name: actualbudget
        restart: unless-stopped
        ports:
            - ${ACTUALBUDGET_HTTP_PORT}:5006
        environment:
            - ACTUAL_ALLOWED_LOGIN_METHODS=password
            - ACTUAL_LOGIN_METHOD=password
            - ACTUAL_PORT=5006
        volumes:
            - ./data:/data
        healthcheck:
            test: ['CMD-SHELL', 'node src/scripts/health-check.js']
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 20s
